friendly_name=NoSocial Movies
media_dir=V,/media/storage/Movies
db_dir=/var/cache/minidlna
log_dir=/var/cache/minidlna
inotify=yes
strict_dlna=no
notify_interval=60
port=8200
presentation_url=http://nosocial.life/app/home
album_art_names=Cover.jpg/cover.jpg/Folder.jpg/folder.jpg
