friendly_name=NoSocial Movies
model_name=NoSocial DLNA Server
model_number=1
serial=nosocial-dlna
media_dir=V,/media/storage/Movies
db_dir=/var/cache/minidlna
log_dir=/var/cache/minidlna
inotify=yes
strict_dlna=no
enable_tivo=no
max_connections=50
notify_interval=30
port=8200
presentation_url=http://192.168.88.201:8200
root_container=B
album_art_names=Cover.jpg/cover.jpg/Folder.jpg/folder.jpg
